<?xml version="1.0"?>
<package format="3">

  <name>vajra_sensors</name>

  <version>0.0.1</version>

  <description>
    VAJRA mine rescue rover sensor simulator
  </description>

  <maintainer email="vajra@example.com">
    vajra
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>
